### ISSUE TITLE
HashMap has bug  after add and remove many times.

### ISSUE THREAD

**Issue by janckerchen** [dingmaotu/mql4-lib#4]
call these step, it failed to remove element #25.  

```
class MyHash : public HashMap<int, int> {

public:
  void test() {
    set(1,1);
    set(2,1);
    set(3,1);
    set(4,1);
    set(5,1);
    set(6,1);
    set(7,1);
    set(8,1);
    set(9,1);
    remove(3);
    remove(4);
    remove(5);
    remove(6);
    remove(7);
    remove(8);
    set(10,1);
    set(11,1);
    set(12,1);
    set(13,1);
    set(14,1);
    set(15,1);
    remove(12);
    remove(13);
    remove(14);
    set(16,1);
    set(17,1);
    set(18,1);
    set(19,1);
    set(20,1);
    set(21,1);
    set(22,1);
    remove(16);
    remove(17);
    remove(18);
    remove(19);
    remove(20);
    remove(21);
    remove(22);
    set(23,1);
    set(24,1);
    set(25,1);
    set(26,1);
    set(27,1);
    remove(23);
    if (remove(25))
      PrintFormat("remove 25 ok %d", this[25]);
    else
      Print("remove 25 failed");     <-- goes here, this[25] == -1 actually
  }
}
```

**Comment by janckerchen** [comment]
I cant understand the implement of hashmap,  need help!  I use HashMap in my core logic.

**Comment by dingmaotu** [comment]
This is a bug caused by a problem I know for a while. You know in MQL you can assign NULL to any type, but this NULL value is not the same. For integer types, it is zero; for string, it is empty string. For pointer, it is NULL pointer. I thought it is the same value but it is not. This false assumption is used to design ArrayCompact and HashMap, and causes problems if you use simple integer types for the key, because hash values can be zero (same as NULL indicating no value).

I can fix HashMap in this particular case by introducing an additional bool array, but I want to find a better solution to represent invalid values of any type without the extra cost. I will fix this soon.

**Comment by dingmaotu** [comment]
It turns out not to be the problem of ArrayCompact used in HashMap. The main problem is an implementation flaw (not dealing with removing and resizing correctly). I updated the code. You've done an excellent job providing this test case. Thanks.

**Comment by janckerchen** [comment]
it works,  good job~,  you save me a lot.
